name: launcherx
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # device_apps: ^1.2.0
  flutter_staggered_grid_view: ^0.3.0
  get: ^3.22.2
  get_storage: ^1.3.2
  launcher_assist: ^1.1.3
  permission_handler: null

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
